### ISSUE TITLE
Checking is_alive status for terminal_group fails

### ISSUE THREAD

**Issue by em-ex** [kebrick/pyiikocloudapi#2]
Thanks for making your library available - saved me a few hours of work. However, `models.py` class `BaseTGIsAliveyModel` (sic!) on line 439 seems to use wrong base class to return results:
```python
class BaseTGIsAliveyModel(BaseResponseModel):
    is_alive_status: Optional[List[StreetsItemModel]] = Field(alias="isAliveStatus")
```
Upon quick source code inspection and monkey-patching, I believe its `is_alive_status` field should be defined like this in order to return anything but Pydantic model validation errors:
```python
    is_alive_status: Optional[List[TGIsAliveItemModel]] = Field(alias="isAliveStatus")
```

**Comment by kebrick** [comment]
@em-ex  OU
I just saw it now, I'll fix it.
Thank you very much for your help :)
