### ISSUE TITLE
Compatibility with newer Pydantic versions?

### ISSUE THREAD

**Issue by em-ex** [kebrick/pyiikocloudapi#4]
I've had to recreate my dev environment recently on a new machine and have forgotten to pin version number for Pydantic. Spent uncomfortably long time scratching my head before I realized why my code was throwing 538 validation errors when pyiikocloudapi requested an external menu...

Which brings me to the question: are there any plans to make your package compatible with newer versions of Pydantic?

PS. By the way, I got it working with slightly newer version (1.10.7) than what you pinned it to in your `requirements.txt` (1.9.1)

**Comment by kebrick** [comment]
I planned to test the work on pydantic version 2.7.4 in mid-November. But thanks to your request, I will try to test with a newer version of pydantic 2.9.2 in the near future and release an update.

**Comment by kebrick** [comment]
The update is complete. Update version 0.0.20

**Comment by em-ex** [comment]
Thank you! Will update and test during the week!
